id: AB968E4A4
title: Guru Sādhana of the Omniscient Dolpopa
type: translation
pechas:
- I8B4B35E8
- I1D9689E3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:12:24.012436
  last_modified_at: 2023-01-04 12:12:24.012448
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I8B4B35E8/0016: '4559'
  I1D9689E3/A9B3: '4559'
